import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "../components/ui/tooltip";
import { ConvexClientProvider } from "../components/ConvexClientProvider";
import QueryProvider from "../lib/QueryProvider";

// Load fonts (make sure `display: "swap"` or similar is added for safety)
const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable}`}
        >
          <body className="antialiased">
            <TooltipProvider>
              <QueryProvider>{children}</QueryProvider>
            </TooltipProvider>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
